config/routes.rb
Rails.application.routes.draw do
  

  get 'login', to: "session#new"
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'

  namespace :admin do
    get 'dashboard/orders'
    get '/dashboard/contacts'
  end


  root 'pages#home', as: 'root'

  get '/about', to: 'pages#about_us'

  get '/products/categories/soft', to: 'pages#categories', as: '/soft'
  get '/products/cans/330ml', to: 'pages#products330', as: '/c330ml'
  get '/products/bottle_drinks', to: 'pages#bottle_drinks', as: '/bottle_drinks'
  get '/products/energy_drinks', to: 'pages#energy_drinks', as: '/energy_drinks'
  get '/products/beer', to: 'pages#beer', as: '/beer'
  get '/products/mineral_water', to: 'pages#mineral_water', as: '/mineral_water'
  get '/products/spirit_drinks', to: 'pages#spirit_alc', as: '/spirit_drinks'


  get '/order-now', to: 'pages#order_now', as: '/order-now'
  post '/order-now', to: 'pages#place_order'
  get '/contact', to: 'pages#contact_us', as: '/contact'
  post '/contact', to: 'pages#create'

   get '/change_locale/:locale', to: 'language#change_locale', as: :change_locale
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
	attr_accessor :remember_token
	validates :name, presence: true
	validates :password, presence: true, length: { minimum: 5 }, allow_nil: true

	has_secure_password


	# Returns the hash digest of the given string.
  def Admin.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #this method returns a random user token
  def Admin.new_token
    SecureRandom.urlsafe_base64
  end

  #this instance method helps to remember a user in the database
  def remember
    self.remember_token = Admin.new_token
    update_attribute(:remember_digest, Admin.digest(remember_token))
  end

  #check if a given token matches that stored one and return true else false
  def authenticated?(remmber_token)
    BCrypt::Password.new(remember_digest).is_password?(remmber_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :first_name, presence: true
	validates :surname, presence: true
	validates  :email, presence: true
    validates	:phone_number, presence: true
    validates	:subject, presence: true
    validates	:content, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
	validates :name_or_business, presence: true
	validates :email, presence: true
	validates :phone, presence: true
	validates :message, presence: true
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
	before_action :logged_in_admin, only: [:orders, :contacts]
  def orders
  	@orders = Order.all
  end

  def contacts
  	@contacts = Contact.all
  end

  private
  def logged_in_admin
   	unless logged_admin?
   		flash[:notice] = "Access denied!"
   		redirect_to login_path
   	end
  end
end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   before_action :set_locale
   include SessionHelper

  def set_locale
  	if cookies[:dash_horgerate] && I18n.available_locales.include?(cookies[:dash_horgerate].to_sym)
  		l = cookies[:dash_horgerate].to_sym
  	  else
  	  	l = "de"
  	  	cookies.permanent[:dash_horgerate] = l
  	end
  	I18n.locale = l
  end
end

app/controllers/language_controller.rb
class LanguageController < ApplicationController
	def change_locale
		l = params[:locale].to_s.strip.to_sym
		l = I18n.default_locale unless I18n.available_locales.include?(l)

		cookies.permanent[:dash_horgerate] = l
		redirect_to request.referer || root_url
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about_us
  end

  def categories
  end

  def products330
    
  end

  def bottle_drinks
    
  end
  def energy_drinks
    
  end
  def beer
    
  end
  def mineral_water
    
  end
  def spirit_alc
    
  end
  def order_now
    @order = Order.new
  end
  def place_order
    @order = Order.new(order_params)
    if @order.save
      flash[:notice] = t('.order_made')
      redirect_to :back
    else
      render 'order_now'
    end
  end

  def contact_us
  	 @contact = Contact.new
  end

  def create
  	@contact = Contact.new(contact_params)
  	if @contact.save
  		flash[:notice] = t('.contact_confirmed')
      redirect_to :back
  	else
  		render 'contact_us'

  	end
  end
  def sitemap
    redirect_to
  end

  private
  def contact_params
    params.require(:contact).permit(:first_name, :surname,
                                    :email, :phone_number,
                                    :subject, :content)
  end

  def order_params
    params.require(:order).permit(:name_or_business, :email,
                                  :phone, :message)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    admin = Admin.find_by(name: params[:session][:name].downcase)

    if admin && admin.authenticate(params[:session][:password])
          log_admin(admin)
          params[:session][:remember_me] == '1' ? remember(admin) : forget(admin)
          redirect_to admin_dashboard_orders_path
    else
      flash.now[:notice] = 'wrong credentials'
      render 'new'
    end

  end

  def destroy
    admin_out if logged_admin?
    redirect_to(root_path)
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/language_helper.rb
module LanguageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
	 #log a given user
  def log_admin(admin)
    session[:admin_id] = admin.id
  end

  #remember a user in a session
  def remember(admin)
    admin.remember
    cookies.permanent.signed[:admin_id] = admin.id
    cookies.permanent[:remember_token] = admin.remember_token
  end

  #returns true if the given user is the current user
  def current_admin?(admin)
    admin == current_admin
  end


  #return the current login user
  def current_admin
    if (admin_id = session[:admin_id])
      @current_admin ||= Admin.find_by(id: session[:admin_id])
    elsif (admin_id = cookies.signed[:admin_id])
      admin = Admin.find_by(id: admin_id)
      if admin && admin.authenticated?(cookies[:remember_token])
        log_admin(admin)
        @current_admin = admin
      end
    end

  end


  #return true if user is logged in
  def logged_admin?
    !current_admin.nil?
  end

  #forget a session
  def forget(admin)
    admin.forget #calling the model method
    cookies.delete(:admin_id)
    cookies.delete(:remember_token)
  end

  #log out the current user
  #this method is used in session controller, to delete users session
  def admin_out
    forget(current_admin)
    session.delete(:admin_id)
    @current_admin = nil
  end
end

app/views/layouts/shared/_products_header.html.erb
 <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'DAS HÖRGERÄTE-ATELIER GMBH',  root_path, class: 'navbar-brand visible-lg', style: "color: #3EB835;"%>
          <%= link_to 'DAS HÖRGERÄTE-ATELIER GMBH',  root_path, class: 'navbar-brand visible-xs visible-sm', style: "color: #3EB835; font-size: .9em"%>
        </div>
        <% if cookies[:dash_horgerate] == "de" %>
          <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left de_locale">
          <li><%= link_to t('.home') , root_path, class: 'active'%></li>
          <li>
            <%= link_to t('.about') , about_path%>
          </li>
          <li>
            <%= link_to t('.products') , soft_path%>
          </li>
          <li>
            <%= link_to t('.order') , order_now_path%>
          </li>
          <li>
            <%= link_to t('.contact') , contact_path%>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
           <li>
            <p style="margin-bottom: 0;">
              <%=t('.call') %> <br>
              <span>+4 915 779 043 003</span>              
            </p>
              <p class="lang">
                <%= link_to 'DE', change_locale_path(:de), style: 'padding-right: 1em'%>|
                <%= link_to 'EN', change_locale_path(:en), style: 'padding-left: 1em'%>
              </p>
           </li>
        </ul>
      </div>
        <%else%>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to t('.home') , root_path, class: 'active'%></li>
          <li>
            <%= link_to t('.about') , about_path%>
          </li>
          <li>
            <%= link_to t('.products') , soft_path%>
          </li>
          <li>
            <%= link_to t('.order') , order_now_path%>
          </li>
          <li>
            <%= link_to t('.contact') , contact_path%>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
           <li>
            <p style="margin-bottom: 0">
              <%=t('.call') %> <br>
              <span>+4 915 779 043 003</span>              
            </p>
              <p class="lang">
                <%= link_to 'DE', change_locale_path(:de), style: 'padding-right: 1em'%>|
                <%= link_to 'EN', change_locale_path(:en), style: 'padding-left: 1em'%>
              </p>
           </li>
        </ul>
      </div>
        <%end%>
    </div>
  </div>

app/views/pages/about_us.html.erb
<%provide(:title, 'About Us') %>
<%=content_for(:about, "about") %>
<div class="row" style="width: 100%">
</div>


 

app/views/pages/beer.html.erb
<%provide(:title, t('pages.categories.beer_header') )  %>
<%=content_for(:product, 'product') %>
<div class="row" style="width: 100%">
	<div class="col-sm-4" style="padding-left: 2rem; padding-top: 2rem">
	 	<div class="row">
	 		<div class="col-sm-12" style="padding-left: 5rem">
	 			<p style="padding: 2rem; 
	 					 background-color: #424242; 
	 					 color: white; 
	 					 width: 60%;
	 					 text-transform: uppercase"><%=t('pages.categories.category') %></p>
	 			<ul class="left-menu">
	 				<li>
	 					<p style="font-weight: bold"><%=t('pages.categories.soft_drinks') %> </p>

	 				</li>
	 				<hr style="margin-left: -10%; 
	 						   width: 70%;
	 						   margin-top: 0; ">
	 				<ul>
	 					<li><span>> </span><%=link_to '250ml', soft_path %></li>
	 					<li><span>>	</span><%=link_to '330ml', c330ml_path %></li>
	 					<li><%=link_to t('pages.categories.pet_bottles') ,bottle_drinks_path  %></li>
	 				
	 				</ul>
	 			</ul>
	 			
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.energy_drinks') , energy_drinks_path %></li>			
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.beer_cat') , beer_path %></li>			
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.mineral_water') ,mineral_water_path %></li>
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.spirits_cat') ,spirit_drinks_path %></li>
	 			</ul>
	 		</div>
	 		<div class="col-sm-12">
	 			<div class="row">
	 				<div class="col-sm-12">
	 					<%= render 'pages/shared/advert2' %>
	 				</div>
	 			</div>
	 		</div>
	 		</div>

	</div>
	<div class="col-sm-8" style="padding-top: 2rem">
			<h3 class="text-center drinks">
				BEER
				<hr>
			</h3>
			<div class="row">
					<div class="col-sm-4">
						<%=image_tag('leffebeer.png', style: 'width: 100%; height: 30rem') %>
						<div class="display">
						<h2>Leffe</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					
					<div class="col-sm-4">
						<%=image_tag('kronenbourg1664.png', style: 'width: 100%; height: 30rem') %>
						<div class="display">
						<h2>Kronenbourg </h2>
						<p>24 x 500ml</p>
						</div>
					</div>
					
					
					<div class="col-sm-4">
						<%=image_tag('carlsbergbeer.png', style: 'width: 100%; height: 30rem') %>
						<div class="display">
						<h2>Carlsberg</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('heineken_500ml_cans.png') %>
						<div class="display">
						<h2>Heineken Cans</h2>
						<p>24 x 500ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('hoegaardenbeer.png', style: 'width: 100%; height: 30rem') %>
						<div class="display">
						<h2>Hoegaarden</h2>
						<p>6 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('coronabeer.png') %>
						<div class="display">
						<h2>Corona Extra</h2>
						<p>6 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('cerveza-coronabeer.png') %>
						<div class="display">
						<h2>Cerveza Corona Extra</h2>
						<p>6 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('heinekenbeer.png') %>
						<div class="display">
						<h2>Heineken</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('cerveza-corona-pack.png') %>
						<div class="display">
						<h2>Corona Extra</h2>
						<p>6 x 355ml</p>
						</div>
					</div>
					

					<div class="col-sm-4">
						<%=image_tag('carlsbergcanbeer.png') %>
						<div class="display">
						<h2>Carlsberg</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('kronenbourg-1664-beer.png') %>
						<div class="display">
						<h2>Kronenbourg 1664</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					
					<div class="col-sm-4">
						<%=image_tag('kronenbourg.png') %>
						<div class="display">
						<h2>Kronenbourg Blanc</h2>
						<p>6 x 330ml</p>
						</div>
					</div>
					
					<div class="col-sm-4">
						<%=image_tag('becks.png') %>
						<div class="display">
						<h2>Becks Vier</h2>
						<p>24 x 275ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('becks-non-alcoholic.png') %>
						<div class="display">
						<h2>Becks Vier</h2>
						<p>24 x 275ml</p>
						</div>
					</div>
					
					

			</div>
	</div>
</div>

app/views/pages/bottle_drinks.html.erb
<%provide(:title, t('pages.categories.pet_header') )  %>
<%=content_for(:product, 'product') %>
<div class="row" style="width: 100%">
	<div class="col-sm-4" style="padding-left: 2rem; padding-top: 2rem">
	 	<div class="row">
	 		<div class="col-sm-12" style="padding-left: 5rem">
	 			<p style="padding: 2rem; 
	 					 background-color: #424242; 
	 					 color: white; 
	 					 width: 60%;
	 					 text-transform: uppercase"><%=t('pages.categories.category')%> </p>
	 			<ul class="left-menu">
	 				<li>
	 					<p style="font-weight: bold"><%=t('pages.categories.soft_drinks') %></p>

	 				</li>
	 				<hr style="margin-left: -10%; 
	 						   width: 70%;
	 						   margin-top: 0; ">
	 				<ul>
	 					<li><span>> </span><%=link_to '250ml', soft_path %></li>
	 					<li><span>>	</span><%=link_to '330ml', c330ml_path %></li>
	 					<li><%=link_to t('pages.categories.pet_bottles') ,bottle_drinks_path  %></li>
	 				
	 				</ul>
	 			</ul>
	 			
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.energy_drinks') , energy_drinks_path %></li>			
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.beer_cat') , beer_path %></li>			
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.mineral_water') ,mineral_water_path %></li>
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.spirits_cat') ,spirit_drinks_path %></li>
	 			</ul>
	 		</div>
	 	</div>
		

	</div>
	<div class="col-sm-8" style="padding-top: 2rem">
			<h3 class="text-center drinks">
				SOFT DRINKS
				<hr>

			</h3>
			<div class="row">
					<div class="col-sm-4">
						<%=image_tag('diet-colabottle.png', width: '100%') %>
						<div class="display">
						<h2>Diet Coke</h2>
						<p>24 x 500ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('coca-colabottle.png', width: '100%') %>
						<div class="display">
						<h2>Coca Cola</h2>
						<p>12 x 1.25L</p>
						</div>
					</div>
					
					<div class="col-sm-4">
						<%=image_tag('lipton-ice-tea-bottle.png', width: '100%') %>
						<div class="display">
						<h2>Lipton Ice Tea</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('7up-bottle.png', width: '100%') %>
						<div class="display">
						<h2>7up </h2>
						<p>12 x 1.5L</p>
						</div>
					</div>
					
					<div class="col-sm-4">
						<%=image_tag('mirandabottle.png', width: '100%') %>
						<div class="display">
						<h2>Miranda</h2>
						<p>12 x 1.5L</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('vimto-still-bottle.png', width: '100%') %>
						<div class="display">
						<h2>Vimto Still</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('coca-zerobottle.png', width: '100%') %>
						<div class="display">
						<h2>Coca Cola Zero Sugar</h2>
						<p>12 x 1.25L</p>
						</div>
					</div>
					
					<div class="col-sm-4">
						<%=image_tag('fanta-orange-bottle.png', width: '100%') %>
						<div class="display">
						<h2>Fanta Orange</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
			</div>
	</div>
</div>

app/views/pages/categories.html.erb
<%provide(:title, '250ml')  %>
<%=content_for(:product, 'product') %>
<div class="row" style="width: 100%">
	<div class="col-sm-4" style="padding-left: 2rem; padding-top: 2rem">
	 	<div class="row">
	 		<div class="col-sm-12" style="padding-left: 5rem">
	 			<p style="padding: 2rem; 
	 					 background-color: #424242; 
	 					 color: white; 
	 					 width: 60%;
	 					 text-transform: uppercase"><%=t('.category')%> </p>
	 			<ul class="left-menu">
	 				<li>
	 					<p style="font-weight: bold"><%=t('.soft_drinks')%> </p>

	 				</li>
	 				<hr style="margin-left: -10%; 
	 						   width: 70%;
	 						   margin-top: 0; ">
	 				<ul>
	 					<li><span>> </span><%=link_to '250ml', soft_path %></li>
	 					<li><span>>	</span><%=link_to '330ml', c330ml_path %></li>
	 					<li><%=link_to t('.pet_bottles') ,bottle_drinks_path  %></li>
	 				
	 				</ul>
	 			</ul>
	 			
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('.energy_drinks') , energy_drinks_path %></li>
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('.beer_cat') , beer_path %></li>			
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('.mineral_water') ,mineral_water_path %></li>
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('.spirits_cat') ,spirit_drinks_path %></li>
	 			</ul>
	 		</div>
	 		<div class="col-sm-12">
	 			<div class="row">
	 				<div class="col-sm-12">
	 					<%= render 'pages/shared/advert' %>
	 				</div>
	 			</div>
	 		</div>
	 		</div>
		

	</div>
	<div class="col-sm-8" style="padding-top: 2rem">
			<h3 class="text-center drinks">
				SOFT DRINKS
				<hr>
			</h3>
			<div class="row">
					<div class="col-sm-4">
						<%=image_tag 'coca-cola-250ml.png', alt: "Coca cola", width: '100%' %>
						<div class="display">
						<h2>Coca Cola 250ml</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('diet-coke-250ml.png', width: '100%') %>
						<div class="display">
						<h2>Diet Coke 250ml</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					
					<div class="col-sm-4">
						<%=image_tag('mirinda-250ml.png', style: "width: 100%;") %>
						<div class="display">
						<h2>Mirinda 250ml</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('7up-250ml.png', style: "width: 100%; padding-top: 2rem") %>
						<div class="display">
						<h2>Mirinda 250ml</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('lipton-ice-tea-250ml.png', style: "width: 100%; padding-top: 2rem") %>
						<div class="display">
						<h2>Liptop Ice Tea 250ml</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('fanta-250ml.png', style: "width: 100%; padding-top: 2rem") %>
						<div class="display">
						<h2>Fanta 250ml</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('sprite-250ml.png', style: "width: 100%; padding-top: 2rem") %>
						<div class="display">
						<h2>Sprite Lemon Lime 250ml</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
			</div>
	</div>
</div>

app/views/pages/energy_drinks.html.erb
<%provide(:title, t('pages.categories.energy_header'))  %>
<%=content_for(:product, 'product') %>
<div class="row" style="width: 100%">
	<div class="col-sm-4" style="padding-left: 2rem; padding-top: 2rem">
	 	<div class="row">
	 		<div class="col-sm-12" style="padding-left: 5rem">
	 			<p style="padding: 2rem; 
	 					 background-color: #424242; 
	 					 color: white; 
	 					 width: 60%;
	 					 text-transform: uppercase"><%=t('pages.categories.category') %> </p>
	 			<ul class="left-menu">
	 				<li>
	 					<p style="font-weight: bold"><%=t('pages.categories.soft_drinks') %> </p>

	 				</li>
	 				<hr style="margin-left: -10%; 
	 						   width: 70%;
	 						   margin-top: 0; ">
	 				<ul>
	 					<li><span>> </span><%=link_to '250ml', soft_path %></li>
	 					<li><span>>	</span><%=link_to '330ml', c330ml_path %></li>
	 					<li><%=link_to t('pages.categories.pet_bottles') ,bottle_drinks_path  %></li>
	 				
	 				</ul>
	 			</ul>
	 			
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.energy_drinks') , energy_drinks_path %></li>			
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.beer_cat') , beer_path %></li>			
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.mineral_water') ,mineral_water_path %></li>
	 			</ul>
	 			<ul class="left-menu cats">
	 				<li><%=link_to t('pages.categories.spirits_cat') ,spirit_drinks_path %></li>
	 			</ul>
	 		</div>
	 	</div>
		

	</div>
	<div class="col-sm-8" style="padding-top: 2rem">
			<h3 class="text-center drinks">
				ENERGY DRINKS
				<hr>

			</h3>
			<div class="row">
					<div class="col-sm-4">
						<%=image_tag('boost-250ml.png', width: '100%') %>
						<div class="display">
						<h2>Boost Energy</h2>
						<p>24 x ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('monster-assault500ml.png', width: '100%') %>
						<div class="display">
						<h2>Monster Assault</h2>
						<p>12 x 500ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('monster-khaos500ml.png', width: '100%') %>
						<div class="display">
						<h2>Monster Khaos</h2>
						<p>12 x 500ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('monster-energy500ml.png', style: "width: 100%; padding-top: 2rem") %>
						<div class="display">
						<h2>Mega Monster Energy</h2>
						<p>12 x 500ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('red-bull500.png',style: "width: 100%; padding-top: 2rem") %>
						<div class="display">
						<h2>Red Bull</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('shark-energy-drink500ml.png', style: "width: 100%; padding-top: 2rem") %>
						<div class="display">
						<h2>Shark Energy</h2>
						<p>24 x 250ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('powerade-ion4bottle.png', style: "width: 100%; padding-top: 2rem") %>
						<div class="display">
						<h2>Powerade Berry & Tropical</h2>
						<p>12 x 500ml</p>
						</div>
					</div>
					<div class="col-sm-4">
						<%=image_tag('boost-energybottle.png', style: "width: 100%; padding-top: 2rem") %>
						<div class="display">
						<h2>Boost Energy Original</h2>
						<p>12 x 500ml</p>
						</div>
					</div>
			</div>
	</div>
</div>